# Generated by Django 6.0.6 on 2026-06-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintproduct',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='paintproduct',
            name='hsn_code',
            field=models.CharField(default='0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='paintproduct',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
